#include <iostream>

/**
 * Even Fibonacci Numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * It is easy to prove that every third Fibonacci number is even.
 * It is not so difficult to change the program somewhat so that only every third number is added:
 *
```
    limit=4000000
    sum=0
    a=1
    b=1
    c=a+b
    while c<limit
        sum=sum+c
        a=b+c
        b=c+a
        c=a+b
    output sum
```
 */
int main() {
    int x = 1;
    int y = 2;
    int z = 0;
    int total = 2;
    do
    {
        z = x + y;
        if(z < 4000000)
        {
            x = y;
            y = z;
            if(z % 2 == 0)
            {
                total += z;
            }
        }
    } while(z <= 4000000);
    printf("total: %d\n", total);
    return 0;
}
